### ISSUE TITLE
Command suggestion

### ISSUE THREAD

**Issue by MrBlasyMSK** [vecnavium-pm-pl/EssentialsX#1]
No /gm0 /gm1 /gm2 /gm3
no start for u

**Comment by Vecnavium** [comment]
So you are saying you prefer having them in numbers for the gamemode instead of gma , gms and etc?

**Comment by Vecnavium** [comment]
And don't open an issue to just say "Bad plugin" with a suggestion /  don't claim it being a bad plugin with no actual reason when the plugin hasn't even been out.

**Comment by MrBlasyMSK** [comment]
> And don't open an issue to just say "Bad plugin" with a suggestion / don't claim it being a bad plugin with no actual reason when the plugin hasn't even been out.

Just joking bro xd but yeah if u add too /gm0 /gm1 etc it would be nice

**Comment by Vecnavium** [comment]
Ahh, my bad lmao and alright I might make it that instead of /gma /gms and etc. thanks for the suggestion

**Comment by Vecnavium** [comment]
Suggestion taken https://github.com/vecnavium-pm-pl/EssentialsX/commit/f03f464d3ebba18cd8f192e1d268ff8992bca928
